repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        name: check-yaml
        description: Attempt to load all yaml files to check the syntax.
      - id: end-of-file-fixer
        name: end-of-file-fixer
        description: Make sure files end in a newline and only a newline.
      - id: fix-encoding-pragma
        name: fix-encoding-pragma
        description: Remove the coding pragma.
        args: [--remove]
      - id: mixed-line-ending
        name: mixed-line-ending
        description: Replace or checks mixed line ending.
        args: [--fix=lf]
      - id: trailing-whitespace
        name: trailing-whitespace
        description: Trim trailing whitespace.
      - id: check-merge-conflict
        name: check-merge-conflict
        description: Check for files that contain merge conflict strings.
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        description: The uncompromising Python code formatter.
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        description: Sort imports alphabetically into sections and by type.
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
      - id: ruff
        name: ruff
        description: An extremely fast Python linter, written in Rust.
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        name: interrogate
        description: Check for missing docstrings.
        args: [--quiet]
        pass_filenames: false
