repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        name: check-yaml
        description: Attempt to load all yaml files to check the syntax
      - id: end-of-file-fixer
        name: end-of-file-fixer
        description: Make sure files end in a newline and only a newline
      - id: mixed-line-ending
        name: mixed-line-ending
        description: Replace or checks mixed line ending
        args: [--fix=lf]
      - id: trailing-whitespace
        name: trailing-whitespace
        description: Trim trailing whitespace
      - id: check-merge-conflict
        name: check-merge-conflict
        description: Check for files that contain merge conflict strings
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: black
        description: The uncompromising Python code formatter
        args: [--line-length=79]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        description: Sort imports alphabetically into sections and by type
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        name: flake8
        description: Your Tool For Style Guide Enforcement
        args: ["--max-line-length", "88"]
